### ISSUE TITLE
Names showing incorrectly at messages to Discord

### ISSUE THREAD

**Issue by Eufranio** [LXGaming/DiscordBot#1]
When peoples from Discord talk, it shows correctly at game.
But when someone in-game send messages to Discord, your nick (only in game) is replaced by %author%. Maybe an conflict of variables.
![screenshot_2](https://cloud.githubusercontent.com/assets/17598280/14765146/8c86ddc8-09aa-11e6-865b-cfde4b7f3567.png)

**Comment by TheLoneWolfNZL** [comment]
@Eufranio Is this the spigot plugin or BC plugin and which version, Could you also attach your config (Remember to remove email and password from it before pasting )

**Comment by Eufranio** [comment]
@TheLoneWolfNZL spigot plugin, - Version 0.3.2 ('Canterbury')
Here's my config: http://pastebin.com/px7uyLtA

**Comment by TheLoneWolfNZL** [comment]
Working on update atm which will include an updated API and a few other features which I hope to release around May 1st
[Read this for more info regarding API Update](https://www.spigotmc.org/resources/discordbot.19347/update?update=85962)

**Comment by Eufranio** [comment]
Okay, i'll wait.
Could you take a look to my another post?https://github.com/LXGaming/DiscordBot/issues/2
Here. Thanks :)

**Comment by LXGaming** [comment]
@Eufranio If you do setup a bot account before 1st may I can send you an early release build of the plugin.

**Comment by Eufranio** [comment]
Ok i'll to do today.

**Comment by Eufranio** [comment]
@LXGaming i did. Could you send me the release?

**Comment by LXGaming** [comment]
https://github.com/LXGaming/DiscordBot/raw/master/Release/DiscordBotSP-jar-with-dependencies.jar

Any issues or of you require assistance just let me know,
Note: it is permission based - DiscordBot.CommandChat - DiscordBot.GlobalChat - DiscordBot.ReceiveDiscordChat

**Comment by Eufranio** [comment]
Okay thanks! :D

**Comment by LXGaming** [comment]
Due to the message sending system changing so much I would guess the %author% bug should be fixed. If not let me know

**Comment by LXGaming** [comment]
@Eufranio New build pushed, should be able to get from same link, Will require you to delete your messages.yml so it can regenerate it.

**Comment by Eufranio** [comment]
`27.04 15:28:35 [Server] WARN at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:633) 27.04 15:28:35 [Server] WARN at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336) 27.04 15:28:35 [Server] WARN at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:447) 27.04 15:28:35 [Server] WARN at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:487) 27.04 15:28:35 [Server] WARN at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:513) 27.04 15:28:35 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) 27.04 15:28:35 [Server] WARN at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) 27.04 15:28:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) 27.04 15:28:35 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) 27.04 15:28:35 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) 27.04 15:28:35 [Server] WARN at io.github.lxgaming.discordbot.DiscordBot.onEnable(DiscordBot.java:35) 27.04 15:28:35 [Server] WARN at io.github.lxgaming.discordbot.DiscordBot.loadDiscord(DiscordBot.java:51) 27.04 15:28:35 [Server] WARN at net.dv8tion.jda.JDABuilder.buildAsync(JDABuilder.java:272) 27.04 15:28:35 [Server] WARN at net.dv8tion.jda.entities.impl.JDAImpl.login(JDAImpl.java:109) 27.04 15:28:35 [Server] WARN java.lang.IllegalArgumentException: The provided email or password as empty / null. 27.04 15:28:35 [Server] INFO [15:28:35] [Info] [JDA]: JDA starting... 27.04 15:28:35 [Server] INFO [15:28:35] [Info] [JDAAudioManager]: Audio System successfully setup! 27.04 15:28:35 [Server] INFO [DiscordBotSP] Enabling DiscordBotSP v0.3.2`
When server is loading the plugin.

**Comment by Eufranio** [comment]
And i have no return when writing /dcc <message> command. Also with global messages.

**Comment by Eufranio** [comment]
Working fine!
