### ISSUE TITLE
[Suggestions] New Discord commands and compatibility

### ISSUE THREAD

**Issue by Eufranio** [LXGaming/DiscordBot#2]
Could you make compatible with chat plugins, like Legendchat?
I want that only messages at Global channel are send to discord, excluding Local messages.

And, if possible, add more discord commands to discord bot like !tps (shows tps from the server), !list (list the players online on server), !ping <player> (shows the ping of an player to server, or vice versa, in ms).

Too, add messages when players joins/quit of the server to discord, like
    Nick joined the game.
    Nick left the game.
customizable.

**Comment by LXGaming** [comment]
Will have to download and test Legendchat,
Getting server tps is not as simple as i expected it to be
Getting player list is added for next version
Getting player ping would have to look into as well
and players joining and leaving servers has been added for next version

**Comment by Eufranio** [comment]
I hope to be added :)

**Comment by LXGaming** [comment]
Source code pushed, Will update spigot and bukkit pages later on ether today or tommorow.
New builds pushed to release folder

**Comment by Eufranio** [comment]
News about LegendChat compatibility?
