### ISSUE TITLE
[Suggestion] Do a .lang file to peoples translate your bot

### ISSUE THREAD

**Issue by Eufranio** [LXGaming/DiscordBot#3]
My server is brazillian, and i want translate the Bot to my idiome (portuguese). It would be great if there was a file that could be translated, then set in config
# Bot lang file: (DEFAULT: en)

lang: pt_br

We could translate by github too :P

**Comment by LXGaming** [comment]
New version contains a messages.yml config file which allows users to customize message formats and I guess even languages too, will have to expand it to support the discord commands

**Comment by Eufranio** [comment]
Customize discord commands too :P

**Comment by LXGaming** [comment]
Alright been working on Language support, creating individual files per language was being a pain so languages go into messages.yml, and locale is set in the config, All Discord events and Commands with there messages are now customizable.
