### ISSUE TITLE
exception while sending the message.

### ISSUE THREAD

**Issue by augesrob** [LXGaming/DiscordBot#5]
18.05 21:33:50 [Server] ERROR [DiscordMC] Discord threw an exception while sending the message. Error on request to https://discordapp.com/api/channels/165521813059796992/messages. Received response code 400. With response text: {"message": "Cannot send an empty message"}

**Comment by LXGaming** [comment]
Make sure the BotChannel and inGameChannel in the config are ID's not names, to get the ID of a channel make sure BotChannel is blank, run the bot and it will output the channels with there ids into console
