### ISSUE TITLE
how do i activate the bot

### ISSUE THREAD

**Issue by KDiaCodes** [LXGaming/DiscordBot#8]
I'm a huge noob when it comes to coding and I cant see a bat file or anything like it. how do I get the bot running

**Comment by LXGaming** [comment]
Which bot version are you trying to run?

DiscordBotBC is for Bungeecord environments (Minecraft)
DiscordBotSP is for Bukkit/Spigot environments (Minecraft)
DiscordBotStandAlone is for any system that can run Java 8

**Comment by KDiaCodes** [comment]
I actually don't know cause I'm a noob sorry
