### ISSUE TITLE
How do I use this plugin?

### ISSUE THREAD

**Issue by steven5297norton** [LXGaming/DiscordBot#9]
I put the DiscordBotSP-0.7.2-jar-with-dependencies.jar in the plugins file on my server

where do I put DiscordBot-master. At the moment I put it in the plugins file.

When I start up the server I get this error

30.09 12:45:18 [Server] ERROR Could not load 'plugins/DiscordBotSP-0.7.2-jar-with-dependencies.jar' in folder 'plugins'

**Comment by LXGaming** [comment]
Try downloading from the link below - What is your server version?

http://jenkins.lolnet.co.nz/view/Lolnet%20Projects/job/DiscordBot/lastSuccessfulBuild/artifact/DiscordBotSP/target/DiscordBotSP-0.7.2-jar-with-dependencies.jar

**Comment by steven5297norton** [comment]
My server version is 1.10.2

I got the same error
